// packages/vue/src/components/Checkbox.vue
<script setup lang="ts">
/**
 * Checkbox Component
 *
 * Vue wrapper for CoralCSS Checkbox component.
 */

import { computed } from 'vue'

export type CheckboxSize = 'sm' | 'md' | 'lg'

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    label?: string
    size?: CheckboxSize
    disabled?: boolean
    error?: boolean
    indeterminate?: boolean
  }>(),
  {
    modelValue: false,
    size: 'md',
    disabled: false,
    error: false,
    indeterminate: false,
  }
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'change', value: boolean): void
}>()

const handleChange = (event: Event) => {
  const target = event.target as HTMLInputElement
  emit('update:modelValue', target.checked)
  emit('change', target.checked)
}
</script>

<template>
  <label
    data-coral-checkbox-wrapper
    :data-size="size"
    :data-error="error || undefined"
    :data-disabled="disabled || undefined"
  >
    <input
      type="checkbox"
      data-coral-checkbox
      :data-size="size"
      :data-indeterminate="indeterminate || undefined"
      :checked="modelValue"
      :disabled="disabled"
      @change="handleChange"
    />
    <span data-coral-checkbox-indicator />
    <span v-if="label" data-coral-checkbox-label>{{ label }}</span>
  </label>
</template>

// packages/react/src/components/Checkbox.tsx
/**
 * Checkbox Component
 *
 * React wrapper for CoralCSS Checkbox component.
 */

import React, { forwardRef, useId } from 'react'

export interface CheckboxProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> {
  /** Label text for the checkbox */
  label?: string
  /** Size variant */
  size?: 'sm' | 'md' | 'lg'
  /** Error state */
  error?: boolean
  /** Indeterminate state */
  indeterminate?: boolean
}

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(
  (
    {
      label,
      size = 'md',
      error = false,
      indeterminate = false,
      className,
      id,
      ...props
    },
    ref
  ) => {
    const generatedId = useId()
    const checkboxId = id || generatedId

    return (
      <label
        data-coral-checkbox-wrapper
        data-size={size}
        data-error={error || undefined}
        data-disabled={props.disabled || undefined}
        className={className}
      >
        <input
          ref={ref}
          type="checkbox"
          id={checkboxId}
          data-coral-checkbox
          data-size={size}
          data-indeterminate={indeterminate || undefined}
          {...props}
        />
        <span data-coral-checkbox-indicator />
        {label && <span data-coral-checkbox-label>{label}</span>}
      </label>
    )
  }
)

Checkbox.displayName = 'Checkbox'
