// packages/vue/src/components/Switch.vue
<script setup lang="ts">
/**
 * Switch Component
 *
 * Vue wrapper for CoralCSS Switch component.
 */

import { computed } from 'vue'

export type SwitchSize = 'sm' | 'md' | 'lg'

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    size?: SwitchSize
    disabled?: boolean
    label?: string
  }>(),
  {
    modelValue: false,
    size: 'md',
    disabled: false,
  }
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'change', value: boolean): void
}>()

const isChecked = computed(() => props.modelValue)

const toggle = () => {
  if (props.disabled) return
  const newValue = !props.modelValue
  emit('update:modelValue', newValue)
  emit('change', newValue)
}

const handleKeydown = (e: KeyboardEvent) => {
  if (e.key === 'Enter' || e.key === ' ') {
    e.preventDefault()
    toggle()
  }
}
</script>

<template>
  <label
    data-coral-switch-wrapper
    :data-disabled="disabled || undefined"
  >
    <button
      type="button"
      role="switch"
      data-coral-switch
      :data-size="size"
      :data-checked="isChecked || undefined"
      :aria-checked="isChecked"
      :disabled="disabled"
      @click="toggle"
      @keydown="handleKeydown"
    >
      <span data-coral-switch-thumb />
    </button>
    <span v-if="label" data-coral-switch-label>{{ label }}</span>
  </label>
</template>

// packages/react/src/components/Switch.tsx
/**
 * Switch Component
 *
 * React wrapper for CoralCSS Switch component.
 */

import React, { forwardRef, useState, useCallback, ButtonHTMLAttributes } from 'react'

export interface SwitchProps extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'> {
  checked?: boolean
  defaultChecked?: boolean
  onCheckedChange?: (checked: boolean) => void
  disabled?: boolean
}

/**
 * Switch component for toggles
 *
 * @example
 * ```tsx
 * const [enabled, setEnabled] = useState(false)
 *
 * <Switch checked={enabled} onCheckedChange={setEnabled} />
 *
 * <label>
 *   <Switch defaultChecked />
 *   <span>Enable notifications</span>
 * </label>
 * ```
 */
export const Switch = forwardRef<HTMLButtonElement, SwitchProps>(
  ({ checked, defaultChecked = false, onCheckedChange, disabled, className, ...props }, ref) => {
    const [internalChecked, setInternalChecked] = useState(defaultChecked)
    const isControlled = checked !== undefined
    const isChecked = isControlled ? checked : internalChecked

    const handleClick = useCallback(() => {
      if (disabled) return

      const newValue = !isChecked
      if (!isControlled) {
        setInternalChecked(newValue)
      }
      onCheckedChange?.(newValue)
    }, [isChecked, isControlled, disabled, onCheckedChange])

    return (
      <button
        ref={ref}
        type="button"
        role="switch"
        aria-checked={isChecked}
        aria-disabled={disabled}
        data-coral-switch=""
        data-checked={isChecked || undefined}
        data-disabled={disabled || undefined}
        disabled={disabled}
        onClick={handleClick}
        className={className}
        {...props}
      >
        <span data-coral-switch-thumb="" />
      </button>
    )
  }
)

Switch.displayName = 'Switch'

export default Switch
