// packages/react/src/components/Badge.tsx
/**
 * Badge Component
 *
 * React wrapper for CoralCSS Badge component.
 */

import React, { forwardRef, HTMLAttributes } from 'react'

export type BadgeVariant =
  | 'default'
  | 'primary'
  | 'secondary'
  | 'destructive'
  | 'success'
  | 'warning'
  | 'outline'

export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  variant?: BadgeVariant
}

/**
 * Badge component for labels and tags
 *
 * @example
 * ```tsx
 * <Badge>Default</Badge>
 * <Badge variant="primary">Primary</Badge>
 * <Badge variant="destructive">Error</Badge>
 * <Badge variant="success">Success</Badge>
 * ```
 */
export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(
  ({ variant = 'default', className, ...props }, ref) => (
    <span
      ref={ref}
      data-coral-badge=""
      data-variant={variant}
      className={className}
      {...props}
    />
  )
)

Badge.displayName = 'Badge'

export default Badge

// packages/vue/src/components/Badge.vue
<script setup lang="ts">
/**
 * Badge Component
 *
 * Vue wrapper for CoralCSS Badge component.
 */

export type BadgeVariant = 'default' | 'secondary' | 'outline' | 'destructive' | 'success' | 'warning'
export type BadgeSize = 'sm' | 'md' | 'lg'

withDefaults(
  defineProps<{
    variant?: BadgeVariant
    size?: BadgeSize
    removable?: boolean
  }>(),
  {
    variant: 'default',
    size: 'md',
    removable: false,
  }
)

const emit = defineEmits<{
  (e: 'remove'): void
}>()
</script>

<template>
  <span
    data-coral-badge
    :data-variant="variant"
    :data-size="size"
  >
    <slot />
    <button
      v-if="removable"
      type="button"
      data-coral-badge-remove
      @click="emit('remove')"
    >
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Remove</span>
    </button>
  </span>
</template>
