// packages/react/src/components/Separator.tsx
/**
 * Separator Component
 *
 * React wrapper for CoralCSS Separator component.
 */

import React, { forwardRef, HTMLAttributes } from 'react'

export interface SeparatorProps extends HTMLAttributes<HTMLDivElement> {
  orientation?: 'horizontal' | 'vertical'
  decorative?: boolean
}

/**
 * Separator component for visual separation
 *
 * @example
 * ```tsx
 * <Separator />
 * <Separator orientation="vertical" />
 * ```
 */
export const Separator = forwardRef<HTMLDivElement, SeparatorProps>(
  ({ orientation = 'horizontal', decorative = true, className, ...props }, ref) => (
    <div
      ref={ref}
      role={decorative ? 'none' : 'separator'}
      aria-orientation={decorative ? undefined : orientation}
      data-coral-separator=""
      data-orientation={orientation}
      className={className}
      {...props}
    />
  )
)

Separator.displayName = 'Separator'

export default Separator

// packages/vue/src/components/Separator.vue
<script setup lang="ts">
/**
 * Separator Component
 */

defineProps<{
  orientation?: 'horizontal' | 'vertical'
  decorative?: boolean
}>()
</script>

<template>
  <div
    :role="decorative !== false ? 'none' : 'separator'"
    :aria-orientation="decorative !== false ? undefined : orientation"
    data-coral-separator=""
    :data-orientation="orientation || 'horizontal'"
  />
</template>
