// packages/react/src/components/Textarea.tsx
/**
 * Textarea Component
 *
 * React wrapper for CoralCSS Textarea component.
 */

import React, { forwardRef, TextareaHTMLAttributes } from 'react'

export interface TextareaProps extends TextareaHTMLAttributes<HTMLTextAreaElement> {
  variant?: 'default' | 'filled' | 'ghost'
  resize?: 'none' | 'vertical' | 'horizontal' | 'both'
  error?: boolean
}

/**
 * Textarea component for multi-line text input
 *
 * @example
 * ```tsx
 * <Textarea placeholder="Enter your message..." rows={4} />
 * ```
 */
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(
  ({ variant = 'default', resize = 'vertical', error, className, ...props }, ref) => (
    <textarea
      ref={ref}
      data-coral-textarea=""
      data-variant={variant}
      data-resize={resize}
      data-error={error || undefined}
      className={className}
      {...props}
    />
  )
)

Textarea.displayName = 'Textarea'

export default Textarea

// packages/vue/src/components/Textarea.vue
<script setup lang="ts">
/**
 * Textarea Component
 */

defineProps<{
  modelValue?: string
  variant?: 'default' | 'filled' | 'ghost'
  resize?: 'none' | 'vertical' | 'horizontal' | 'both'
  error?: boolean
  placeholder?: string
  rows?: number
  disabled?: boolean
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
}>()
</script>

<template>
  <textarea
    data-coral-textarea=""
    :data-variant="variant || 'default'"
    :data-resize="resize || 'vertical'"
    :data-error="error || undefined"
    :value="modelValue"
    :placeholder="placeholder"
    :rows="rows"
    :disabled="disabled"
    @input="emit('update:modelValue', ($event.target as HTMLTextAreaElement).value)"
  />
</template>
